spring.application.name=FabiDoces
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/Spring
spring.datasource.username=SpringAcess
spring.datasource.password=SpringAcess
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl.auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fabidoces.do.not.reply@gmail.com
spring.mail.password=htko jnjn xsgi uvoo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
