spring.application.name=client-service

spring.servlet.multipart.max-file-size=4MB
spring.servlet.multipart.max-request-size=4MB
spring.servlet.multipart.location=${java.io.tmpdir}
server.tomcat.max-swallow-size=-1
